In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('lista_dados_sage.csv',sep=';')

In [4]:
import datetime

In [5]:
df.head()

,ibge,uf,cidade,n_semana,n_ano,total_acumulado,total_investigacao,total_confirmado,total_descartado,total_obito_notificado,total_obito_investigado,total_obito_confirmado,total_obito_descartado
0,120001,AC,Acrelândia,6,2016,0,0,0,0,0,0,0,0
1,120005,AC,Assis Brasil,6,2016,0,0,0,0,0,0,0,0
2,120010,AC,Brasiléia,6,2016,0,0,0,0,0,0,0,0
3,120010,AC,Brasiléia,37,2016,1,1,0,0,0,0,0,0
4,120010,AC,Brasiléia,38,2016,1,1,0,0,0,0,0,0

In [7]:
df['LastDayWeek'] = pd.to_datetime((df['n_ano']).astype(str) + (df['n_semana']-1).astype(str) + "6", format="%Y%U%w")

In [8]:
df

,ibge,uf,cidade,n_semana,n_ano,total_acumulado,total_investigacao,total_confirmado,total_descartado,total_obito_notificado,total_obito_investigado,total_obito_confirmado,total_obito_descartado,LastDayWeek
0,120001,AC,Acrelândia,6,2016,0,0,0,0,0,0,0,0,2016-02-06
1,120005,AC,Assis Brasil,6,2016,0,0,0,0,0,0,0,0,2016-02-06
2,120010,AC,Brasiléia,6,2016,0,0,0,0,0,0,0,0,2016-02-06
3,120010,AC,Brasiléia,37,2016,1,1,0,0,0,0,0,0,2016-09-10
4,120010,AC,Brasiléia,38,2016,1,1,0,0,0,0,0,0,2016-09-17
5,120010,AC,Brasiléia,39,2016,1,1,0,0,0,0,0,0,2016-09-24
6,120010,AC,Brasiléia,40,2016,1,1,0,0,0,0,0,0,2016-10-01
7,120010,AC,Brasiléia,41,2016,1,1,0,0,0,0,0,0,2016-10-08
8,120010,AC,Brasiléia,42,2016,1,1,0,0,0,0,0,0,2016-10-15
9,120010,AC,Brasiléia,43,2016,1,1,0,0,0,0,0,0,2016-10-22
10,120010,AC,Brasiléia,44,2016,1,1,0,0,0,0,0,0,2016-10-29
11,120010,AC,Brasiléia,45,2016,1,1,0,0,0,0,0,0,2016-11-05
12,120010,AC,Brasiléia,46,2016,1,1,0,0,0,0,0,0,2016-11-12
13,120010,AC,Brasiléia,47,2016,1,1,0,0,0,0,0,0,2016-11-19
14,120010,AC,Brasiléia,48,2016,1,1,0,0,0,0,0,0,2016-11-26
15,120010,AC,Brasiléia,50,2016,1,1,0,0,0,0,0,0,2016-12-10
16,120013,AC,Bujari,6,2016,0,0,0,0,0,0,0,0,2016-02-06
17,120017,AC,Capixaba,6,2016,0,0,0,0,0,0,0,0,2016-02-06
18,120017,AC,Capixaba,44,2016,1,1,0,0,0,0,0,0,2016-10-29
19,120017,AC,Capixaba,45,2016,1,1,0,0,0,0,0,0,2016-11-05
20,120017,AC,Capixaba,46,2016,1,1,0,0,0,0,0,0,2016-11-12
21,120017,AC,Capixaba,47,2016,1,1,0,0,0,0,0,0,2016-11-19
22,120017,AC,Capixaba,48,2016,1,1,0,0,0,0,0,0,2016-11-26
23,120017,AC,Capixaba,50,2016,1,1,0,0,0,0,0,0,2016-12-10
24,120020,AC,Cruzeiro do Sul,6,2016,1,1,0,0,0,0,0,0,2016-02-06
25,120020,AC,Cruzeiro do Sul,7,2016,1,1,0,0,0,0,0,0,2016-02-13
26,120020,AC,Cruzeiro do Sul,8,2016,1,1,0,0,0,0,0,0,2016-02-20
27,120020,AC,Cruzeiro do Sul,9,2016,1,1,0,0,0,0,0,0,2016-02-27
28,120020,AC,Cruzeiro do Sul,10,2016,1,1,0,0,0,0,0,0,2016-03-05
29,120020,AC,Cruzeiro do Sul,11,2016,1,1,0,0,0,0,0,0,2016-03-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67213,172210,TO,Xambioá,20,2016,1,0,0,1,0,0,0,0,2016-05-14
67214,172210,TO,Xambioá,21,2016,1,0,0,1,0,0,0,0,2016-05-21
67215,172210,TO,Xambioá,22,2016,1,0,0,1,0,0,0,0,2016-05-28
67216,172210,TO,Xambioá,23,2016,1,0,0,1,0,0,0,0,2016-06-04
67217,172210,TO,Xambioá,24,2016,1,0,0,1,0,0,0,0,2016-06-11
67218,172210,TO,Xambioá,25,2016,1,0,0,1,0,0,0,0,2016-06-18
67219,172210,TO,Xambioá,26,2016,1,0,0,1,0,0,0,0,2016-06-25
67220,172210,TO,Xambioá,27,2016,1,0,0,1,0,0,0,0,2016-07-02
67221,172210,TO,Xambioá,28,2016,1,0,0,1,0,0,0,0,2016-07-09
67222,172210,TO,Xambioá,29,2016,1,0,0,1,0,0,0,0,2016-07-16
67223,172210,TO,Xambioá,30,2016,1,0,0,1,0,0,0,0,2016-07-23
67224,172210,TO,Xambioá,31,2016,1,0,0,1,0,0,0,0,2016-07-30
67225,172210,TO,Xambioá,32,2016,1,0,0,1,0,0,0,0,2016-08-06
67226,172210,TO,Xambioá,33,2016,1,0,0,1,0,0,0,0,2016-08-13
67227,172210,TO,Xambioá,34,2016,1,0,0,1,0,0,0,0,2016-08-20
67228,172210,TO,Xambioá,35,2016,1,0,0,1,0,0,0,0,2016-08-27
67229,172210,TO,Xambioá,36,2016,1,0,0,1,0,0,0,0,2016-09-03
67230,172210,TO,Xambioá,37,2016,1,0,0,1,0,0,0,0,2016-09-10
67231,172210,TO,Xambioá,38,2016,1,0,0,1,0,0,0,0,2016-09-17
67232,172210,TO,Xambioá,39,2016,1,0,0,1,0,0,0,0,2016-09-24
67233,172210,TO,Xambioá,40,2016,1,0,0,1,0,0,0,0,2016-10-01
67234,172210,TO,Xambioá,41,2016,1,0,0,1,0,0,0,0,2016-10-08
67235,172210,TO,Xambioá,42,2016,1,0,0,1,0,0,0,0,2016-10-15
67236,172210,TO,Xambioá,43,2016,1,0,0,1,0,0,0,0,2016-10-22
67237,172210,TO,Xambioá,44,2016,1,0,0,1,0,0,0,0,2016-10-29
67238,172210,TO,Xambioá,45,2016,1,0,0,1,0,0,0,0,2016-11-05
67239,172210,TO,Xambioá,46,2016,1,0,0,1,0,0,0,0,2016-11-12
67240,172210,TO,Xambioá,47,2016,1,0,0,1,0,0,0,0,2016-11-19
67241,172210,TO,Xambioá,48,2016,1,0,0,1,0,0,0,0,2016-11-26
67242,172210,TO,Xambioá,50,2016,1,0,0,1,0,0,0,0,2016-12-10

In [13]:
type('LastDayWeek')

str

In [14]:
print(df.index)

RangeIndex(start=0, stop=67243, step=1)

In [31]:
df.resample('M').sum()

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'RangeIndex'

In [17]:
df.groupby('LastDayWeek').resample('M').sum()

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'RangeIndex'

In [25]:
len(df1.groups)

2179

In [26]:
df.count()

ibge                       67243
uf                         67243
cidade                     67243
n_semana                   67243
n_ano                      67243
total_acumulado            67243
total_investigacao         67243
total_confirmado           67243
total_descartado           67243
total_obito_notificado     67243
total_obito_investigado    67243
total_obito_confirmado     67243
total_obito_descartado     67243
LastDayWeek                67243
dtype: int64

In [27]:
ordena_cidades = df1.size()

In [28]:
ordena_cidades

cidade
Abadiânia                 44
Abaetetuba                44
Abaeté                     3
Abaré                     18
Abaíra                     1
Abreu e Lima              44
Acajutiba                 41
Acarape                   44
Acaraú                    44
Acari                      1
Acará                      7
Acrelândia                 1
Adustina                   1
Afogados da Ingazeira     44
Afonso Bezerra            38
Afonso Cláudio            17
Afrânio                   40
Agrestina                 44
Aguanil                   22
Aguiar                    44
Aguiarnópolis             39
Aiquara                    1
Alagoa Grande             16
Alagoa Nova               44
Alagoinha                 75
Alagoinhas                44
Alcantil                  44
Alcobaça                   1
Alcântara                 42
Alcântaras                39
                        ...
Votuporanga               44
Várzea                    45
Várzea Alegre             41
Várzea Branca             44
Várzea Grande             82
Várzea Nova                1
Várzea Paulista           36
Várzea da Roça            44
Várzea do Poço             1
Wagner                     1
Wanderley                 44
Wanderlândia              44
Wenceslau Guimarães        1
Xambioá                   44
Xanxerê                   11
Xapuri                     1
Xaxim                     18
Xexéu                     44
Xique-Xique               44
Zabelê                    44
Zacarias                  38
Zé Doca                   39
Água Boa                   5
Água Branca              128
Água Fria                  1
Água Nova                  1
Água Preta                44
Águas Belas               44
Águas Lindas de Goiás     43
Érico Cardoso              1
Length: 2179, dtype: int64

In [29]:
ordena_cidades.sort_values()

cidade
Lajes Pintadas               1
Jaborandi                    1
Jacaraci                     1
Jacaré dos Homens            1
Jacundá                      1
Jacuípe                      1
Janaúba                      1
Jaramataia                   1
Jardim de Angicos            1
Ivoti                        1
Jardim do Seridó             1
Jericó                       1
Jiquiriçá                    1
Jitaúna                      1
José da Penha                1
João Dias                    1
Juarez Távora                1
Jucuruçu                     1
Jussari                      1
Jequiá da Praia              1
Ivinhema                     1
Iuiú                         1
Ituberá                      1
Iraquara                     1
Itabi                        1
Itaguaçu da Bahia            1
Itaju do Colônia             1
Italva                       1
Itamaraju                    1
Itamari                      1
                          ...
Rio Branco                  88
Pacatuba                    88
Pilar                       88
Pilões                      88
Itabaiana                   88
Riachuelo                   88
Parnamirim                  88
Conde                       88
Campo Grande                88
Taperoá                     88
Santa Inês                  88
Brejinho                    88
São Sebastião               88
Morrinhos                   88
Batalha                     88
Santa Teresinha             88
Vera Cruz                   88
Itaporanga                  88
Esperantina                 88
São Gonçalo do Amarante     88
Condado                     88
Valença                     88
Capela                      88
Belém                       89
Viçosa                      89
Santa Cruz                  89
Bonito                      93
Nova Olinda                106
Água Branca                128
Santa Luzia                162
Length: 2179, dtype: int64

In [30]:
df

,ibge,uf,cidade,n_semana,n_ano,total_acumulado,total_investigacao,total_confirmado,total_descartado,total_obito_notificado,total_obito_investigado,total_obito_confirmado,total_obito_descartado,LastDayWeek
0,120001,AC,Acrelândia,6,2016,0,0,0,0,0,0,0,0,2016-02-06
1,120005,AC,Assis Brasil,6,2016,0,0,0,0,0,0,0,0,2016-02-06
2,120010,AC,Brasiléia,6,2016,0,0,0,0,0,0,0,0,2016-02-06
3,120010,AC,Brasiléia,37,2016,1,1,0,0,0,0,0,0,2016-09-10
4,120010,AC,Brasiléia,38,2016,1,1,0,0,0,0,0,0,2016-09-17
5,120010,AC,Brasiléia,39,2016,1,1,0,0,0,0,0,0,2016-09-24
6,120010,AC,Brasiléia,40,2016,1,1,0,0,0,0,0,0,2016-10-01
7,120010,AC,Brasiléia,41,2016,1,1,0,0,0,0,0,0,2016-10-08
8,120010,AC,Brasiléia,42,2016,1,1,0,0,0,0,0,0,2016-10-15
9,120010,AC,Brasiléia,43,2016,1,1,0,0,0,0,0,0,2016-10-22
10,120010,AC,Brasiléia,44,2016,1,1,0,0,0,0,0,0,2016-10-29
11,120010,AC,Brasiléia,45,2016,1,1,0,0,0,0,0,0,2016-11-05
12,120010,AC,Brasiléia,46,2016,1,1,0,0,0,0,0,0,2016-11-12
13,120010,AC,Brasiléia,47,2016,1,1,0,0,0,0,0,0,2016-11-19
14,120010,AC,Brasiléia,48,2016,1,1,0,0,0,0,0,0,2016-11-26
15,120010,AC,Brasiléia,50,2016,1,1,0,0,0,0,0,0,2016-12-10
16,120013,AC,Bujari,6,2016,0,0,0,0,0,0,0,0,2016-02-06
17,120017,AC,Capixaba,6,2016,0,0,0,0,0,0,0,0,2016-02-06
18,120017,AC,Capixaba,44,2016,1,1,0,0,0,0,0,0,2016-10-29
19,120017,AC,Capixaba,45,2016,1,1,0,0,0,0,0,0,2016-11-05
20,120017,AC,Capixaba,46,2016,1,1,0,0,0,0,0,0,2016-11-12
21,120017,AC,Capixaba,47,2016,1,1,0,0,0,0,0,0,2016-11-19
22,120017,AC,Capixaba,48,2016,1,1,0,0,0,0,0,0,2016-11-26
23,120017,AC,Capixaba,50,2016,1,1,0,0,0,0,0,0,2016-12-10
24,120020,AC,Cruzeiro do Sul,6,2016,1,1,0,0,0,0,0,0,2016-02-06
25,120020,AC,Cruzeiro do Sul,7,2016,1,1,0,0,0,0,0,0,2016-02-13
26,120020,AC,Cruzeiro do Sul,8,2016,1,1,0,0,0,0,0,0,2016-02-20
27,120020,AC,Cruzeiro do Sul,9,2016,1,1,0,0,0,0,0,0,2016-02-27
28,120020,AC,Cruzeiro do Sul,10,2016,1,1,0,0,0,0,0,0,2016-03-05
29,120020,AC,Cruzeiro do Sul,11,2016,1,1,0,0,0,0,0,0,2016-03-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67213,172210,TO,Xambioá,20,2016,1,0,0,1,0,0,0,0,2016-05-14
67214,172210,TO,Xambioá,21,2016,1,0,0,1,0,0,0,0,2016-05-21
67215,172210,TO,Xambioá,22,2016,1,0,0,1,0,0,0,0,2016-05-28
67216,172210,TO,Xambioá,23,2016,1,0,0,1,0,0,0,0,2016-06-04
67217,172210,TO,Xambioá,24,2016,1,0,0,1,0,0,0,0,2016-06-11
67218,172210,TO,Xambioá,25,2016,1,0,0,1,0,0,0,0,2016-06-18
67219,172210,TO,Xambioá,26,2016,1,0,0,1,0,0,0,0,2016-06-25
67220,172210,TO,Xambioá,27,2016,1,0,0,1,0,0,0,0,2016-07-02
67221,172210,TO,Xambioá,28,2016,1,0,0,1,0,0,0,0,2016-07-09
67222,172210,TO,Xambioá,29,2016,1,0,0,1,0,0,0,0,2016-07-16
67223,172210,TO,Xambioá,30,2016,1,0,0,1,0,0,0,0,2016-07-23
67224,172210,TO,Xambioá,31,2016,1,0,0,1,0,0,0,0,2016-07-30
67225,172210,TO,Xambioá,32,2016,1,0,0,1,0,0,0,0,2016-08-06
67226,172210,TO,Xambioá,33,2016,1,0,0,1,0,0,0,0,2016-08-13
67227,172210,TO,Xambioá,34,2016,1,0,0,1,0,0,0,0,2016-08-20
67228,172210,TO,Xambioá,35,2016,1,0,0,1,0,0,0,0,2016-08-27
67229,172210,TO,Xambioá,36,2016,1,0,0,1,0,0,0,0,2016-09-03
67230,172210,TO,Xambioá,37,2016,1,0,0,1,0,0,0,0,2016-09-10
67231,172210,TO,Xambioá,38,2016,1,0,0,1,0,0,0,0,2016-09-17
67232,172210,TO,Xambioá,39,2016,1,0,0,1,0,0,0,0,2016-09-24
67233,172210,TO,Xambioá,40,2016,1,0,0,1,0,0,0,0,2016-10-01
67234,172210,TO,Xambioá,41,2016,1,0,0,1,0,0,0,0,2016-10-08
67235,172210,TO,Xambioá,42,2016,1,0,0,1,0,0,0,0,2016-10-15
67236,172210,TO,Xambioá,43,2016,1,0,0,1,0,0,0,0,2016-10-22
67237,172210,TO,Xambioá,44,2016,1,0,0,1,0,0,0,0,2016-10-29
67238,172210,TO,Xambioá,45,2016,1,0,0,1,0,0,0,0,2016-11-05
67239,172210,TO,Xambioá,46,2016,1,0,0,1,0,0,0,0,2016-11-12
67240,172210,TO,Xambioá,47,2016,1,0,0,1,0,0,0,0,2016-11-19
67241,172210,TO,Xambioá,48,2016,1,0,0,1,0,0,0,0,2016-11-26
67242,172210,TO,Xambioá,50,2016,1,0,0,1,0,0,0,0,2016-12-10

In [36]:
df['LastDayWeek'] = pd.to_datetime(df['LastDayWeek'])

In [37]:
type(df['LastDayWeek'])

pandas.core.series.Series

In [42]:
df['mes'] = df["LastDayWeek"].apply( lambda df : 
datetime.datetime(year=df.year, month=df.month, day=df.day))

In [44]:
df.resample('M').sum()

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'RangeIndex'

In [45]:
df['LastDayWeek'] = pd.to_datetime(df['LastDayWeek'], errors='coerce')

In [46]:
df.resample('M').sum()

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'RangeIndex'