In [61]:
import pickle
import pandas as pd

In [62]:
file_name = 'C:\\Users\\Vinicius\\Downloads\\IBGE_Mun'
infile = open(file_name,'rb')
new_dict = pickle.load(infile)
infile.close()

#dados do IBGE  data\\IBGE
abre_IBGE_MunTot = new_dict['IBGE_Mun']

In [35]:
#abre_IBGE_MunTot.groupby("ANO").ANO.count()

ANO
1991    5565
2000    5565
2010    5565
Name: ANO, dtype: int64

In [63]:
abre_IBGE_MunTot_2010 = abre_IBGE_MunTot.where(abre_IBGE_MunTot.ANO == 2010).dropna()

In [64]:
dados_sage = pd.read_csv('C:\\Users\\Vinicius\\Downloads\\lista_dados_sage.csv', delimiter=";")

In [51]:
#abre_IBGE_MunTot_2010.where(abre_IBGE_MunTot_2010.Codmun6 == 120001).dropna() #.

,ANO,UF,Codmun6,Codmun7,Município,T_AGUA,T_BANAGUA,T_DENS,T_LIXO,T_LUZ,AGUA_ESGOTO
11182,2010.0,12.0,120001.0,1200013.0,ACRELÂNDIA,93.87,55.29,41.61,97.44,94.56,23.82

In [55]:
#dados_sage

,ibge,uf,cidade,n_semana,n_ano,total_acumulado,total_investigacao,total_confirmado,total_descartado,total_obito_notificado,total_obito_investigado,total_obito_confirmado,total_obito_descartado
0,120001,AC,Acrelândia,6,2016,0,0,0,0,0,0,0,0
1,120005,AC,Assis Brasil,6,2016,0,0,0,0,0,0,0,0
2,120010,AC,Brasiléia,6,2016,0,0,0,0,0,0,0,0
3,120010,AC,Brasiléia,37,2016,1,1,0,0,0,0,0,0
4,120010,AC,Brasiléia,38,2016,1,1,0,0,0,0,0,0
5,120010,AC,Brasiléia,39,2016,1,1,0,0,0,0,0,0
6,120010,AC,Brasiléia,40,2016,1,1,0,0,0,0,0,0
7,120010,AC,Brasiléia,41,2016,1,1,0,0,0,0,0,0
8,120010,AC,Brasiléia,42,2016,1,1,0,0,0,0,0,0
9,120010,AC,Brasiléia,43,2016,1,1,0,0,0,0,0,0
10,120010,AC,Brasiléia,44,2016,1,1,0,0,0,0,0,0
11,120010,AC,Brasiléia,45,2016,1,1,0,0,0,0,0,0
12,120010,AC,Brasiléia,46,2016,1,1,0,0,0,0,0,0
13,120010,AC,Brasiléia,47,2016,1,1,0,0,0,0,0,0
14,120010,AC,Brasiléia,48,2016,1,1,0,0,0,0,0,0
15,120010,AC,Brasiléia,50,2016,1,1,0,0,0,0,0,0
16,120013,AC,Bujari,6,2016,0,0,0,0,0,0,0,0
17,120017,AC,Capixaba,6,2016,0,0,0,0,0,0,0,0
18,120017,AC,Capixaba,44,2016,1,1,0,0,0,0,0,0
19,120017,AC,Capixaba,45,2016,1,1,0,0,0,0,0,0
20,120017,AC,Capixaba,46,2016,1,1,0,0,0,0,0,0
21,120017,AC,Capixaba,47,2016,1,1,0,0,0,0,0,0
22,120017,AC,Capixaba,48,2016,1,1,0,0,0,0,0,0
23,120017,AC,Capixaba,50,2016,1,1,0,0,0,0,0,0
24,120020,AC,Cruzeiro do Sul,6,2016,1,1,0,0,0,0,0,0
25,120020,AC,Cruzeiro do Sul,7,2016,1,1,0,0,0,0,0,0
26,120020,AC,Cruzeiro do Sul,8,2016,1,1,0,0,0,0,0,0
27,120020,AC,Cruzeiro do Sul,9,2016,1,1,0,0,0,0,0,0
28,120020,AC,Cruzeiro do Sul,10,2016,1,1,0,0,0,0,0,0
29,120020,AC,Cruzeiro do Sul,11,2016,1,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
67213,172210,TO,Xambioá,20,2016,1,0,0,1,0,0,0,0
67214,172210,TO,Xambioá,21,2016,1,0,0,1,0,0,0,0
67215,172210,TO,Xambioá,22,2016,1,0,0,1,0,0,0,0
67216,172210,TO,Xambioá,23,2016,1,0,0,1,0,0,0,0
67217,172210,TO,Xambioá,24,2016,1,0,0,1,0,0,0,0
67218,172210,TO,Xambioá,25,2016,1,0,0,1,0,0,0,0
67219,172210,TO,Xambioá,26,2016,1,0,0,1,0,0,0,0
67220,172210,TO,Xambioá,27,2016,1,0,0,1,0,0,0,0
67221,172210,TO,Xambioá,28,2016,1,0,0,1,0,0,0,0
67222,172210,TO,Xambioá,29,2016,1,0,0,1,0,0,0,0
67223,172210,TO,Xambioá,30,2016,1,0,0,1,0,0,0,0
67224,172210,TO,Xambioá,31,2016,1,0,0,1,0,0,0,0
67225,172210,TO,Xambioá,32,2016,1,0,0,1,0,0,0,0
67226,172210,TO,Xambioá,33,2016,1,0,0,1,0,0,0,0
67227,172210,TO,Xambioá,34,2016,1,0,0,1,0,0,0,0
67228,172210,TO,Xambioá,35,2016,1,0,0,1,0,0,0,0
67229,172210,TO,Xambioá,36,2016,1,0,0,1,0,0,0,0
67230,172210,TO,Xambioá,37,2016,1,0,0,1,0,0,0,0
67231,172210,TO,Xambioá,38,2016,1,0,0,1,0,0,0,0
67232,172210,TO,Xambioá,39,2016,1,0,0,1,0,0,0,0
67233,172210,TO,Xambioá,40,2016,1,0,0,1,0,0,0,0
67234,172210,TO,Xambioá,41,2016,1,0,0,1,0,0,0,0
67235,172210,TO,Xambioá,42,2016,1,0,0,1,0,0,0,0
67236,172210,TO,Xambioá,43,2016,1,0,0,1,0,0,0,0
67237,172210,TO,Xambioá,44,2016,1,0,0,1,0,0,0,0
67238,172210,TO,Xambioá,45,2016,1,0,0,1,0,0,0,0
67239,172210,TO,Xambioá,46,2016,1,0,0,1,0,0,0,0
67240,172210,TO,Xambioá,47,2016,1,0,0,1,0,0,0,0
67241,172210,TO,Xambioá,48,2016,1,0,0,1,0,0,0,0
67242,172210,TO,Xambioá,50,2016,1,0,0,1,0,0,0,0

In [66]:
dados_sage_IBGE = dados_sage.set_index('ibge').join(abre_IBGE_MunTot_2010.set_index('Codmun6').drop(columns=['ANO', 'UF', 'Codmun7', 'Município']))

In [70]:
import pickle

pickle.dump(dados_sage_IBGE,open( 'C:\\Users\\Vinicius\\Downloads\\dados_sage_IBGE.p', "wb" ) )
pickle.dump(abre_IBGE_MunTot_2010,open( 'C:\\Users\\Vinicius\\Downloads\\IBGE_Mun', "wb" ) )

In [71]:
teste1 = pickle.load(open( 'C:\\Users\\Vinicius\\Downloads\\dados_sage_IBGE.p', "rb" ) )
teste2 = pickle.load(open( 'C:\\Users\\Vinicius\\Downloads\\IBGE_Mun', "rb" ) )